#!/bin/sh /etc/rc.common

START=95
STOP=15

NAME=ssmgr

start() {
  kill -9 $(ps | grep /usr/share/ssmgr/auto.sh| grep -v grep | awk '{print $1}')
	/usr/share/ssmgr/auto.sh
}

stop() {
	kill -9 $(ps | grep /usr/share/ssmgr/auto.sh| grep -v grep | awk '{print $1}')
}